FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_LINK_MODE=copy \
    UV_PROJECT_ENVIRONMENT=/opt/venv \
    PATH="/root/.local/bin:$PATH" \
    LOG_LEVEL=DEBUG \
    DEBUG=True

WORKDIR /app

RUN apt update \
    && apt install -y --no-install-recommends build-essential curl pkg-config libpq-dev \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /opt/venv \
    && mkdir /usr/sessions

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

COPY pyproject.toml uv.lock* ./

RUN uv sync --dev

RUN uv add watchdog

CMD ["uv", "run", "manage.py", "runserver", "0.0.0.0:8000"]
