# Generated by Django 6.0 on 2025-12-26 22:17

import bot.types
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='title')),
                ('username', models.CharField(blank=True, max_length=256, null=True, verbose_name='@username')),
                ('has_protected_content', models.BooleanField(default=False, verbose_name='has_protected_content')),
                ('last_username_change', models.DateTimeField(blank=True, default=None, null=True, verbose_name='last_username_change_utc')),
                ('history_days_limit', models.PositiveSmallIntegerField(default=30, verbose_name='history_days_limit')),
                ('delete_albums', models.BooleanField(default=True, verbose_name='delete_albums')),
                ('republish_today_posts', models.BooleanField(default=True, verbose_name='republish_today_deleted_posts')),
                ('deletions_count_for_username_change', models.PositiveSmallIntegerField(default=0, help_text='deletions_count_for_username_change_help_text', verbose_name='deletions_count_for_username_change')),
                ('delete_posts_after_days', models.PositiveSmallIntegerField(default=90, verbose_name='delete_all_posts_after_days')),
            ],
            options={
                'verbose_name': 'channel',
                'verbose_name_plural': 'channels',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatlist_invite', models.CharField(blank=True, max_length=16, null=True, verbose_name='chatlist_invite')),
                ('userbots_chat_invite', models.CharField(blank=True, max_length=16, null=True, verbose_name='userbots_chat_invite')),
                ('archive_channel', models.BigIntegerField(blank=True, null=True, verbose_name='archive_channel_id')),
                ('username_suffix_length', models.PositiveSmallIntegerField(default=2, verbose_name='username_suffix_length')),
                ('check_post_views_interval', models.PositiveSmallIntegerField(default=60, verbose_name='check_post_views_interval_seconds')),
                ('check_post_deletions_interval', models.PositiveSmallIntegerField(default=60, verbose_name='check_post_deletions_interval_seconds')),
                ('check_stats_interval', models.PositiveSmallIntegerField(default=120, verbose_name='check_stats_interval_seconds')),
                ('delete_old_posts_interval', models.PositiveSmallIntegerField(default=60, verbose_name='delete_old_posts_interval_minutes')),
                ('username_change_cooldown', models.PositiveSmallIntegerField(default=120, verbose_name='username_change_cooldown_minutes')),
                ('individual_allocations', models.BooleanField(default=False, help_text='individual_allocations_help_text', verbose_name='individual_allocations')),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
            },
        ),
        migrations.CreateModel(
            name='UserBot',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_utc')),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('username', models.CharField(blank=True, max_length=256, null=True, verbose_name='@username')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='last_name')),
                ('phone_number', models.CharField(max_length=32, unique=True, verbose_name='phone_number')),
                ('last_service_message', models.CharField(blank=True, max_length=4096, null=True, verbose_name='last_service_message')),
                ('last_service_message_date', models.DateTimeField(blank=True, null=True, verbose_name='last_service_message_date')),
            ],
            options={
                'verbose_name': 'userbot',
                'verbose_name_plural': 'userbots',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='UserBotConfig',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_utc')),
                ('phone_number', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='phone_number')),
                ('password', models.CharField(blank=True, max_length=64, null=True, verbose_name='password')),
                ('worker_instances', models.PositiveSmallIntegerField(default=1, verbose_name='worker_instances')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
            options={
                'verbose_name': 'userbot',
                'verbose_name_plural': 'userbots',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Excess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_utc')),
                ('type', models.CharField(choices=[(bot.types.LogType['DELETION'], 'deletion'), (bot.types.LogType['USERNAME_CHANGE'], 'username_change')], max_length=16, verbose_name='type')),
                ('reason', models.CharField(blank=True, choices=[(bot.types.UsernameChangeReason['DELETIONS_LIMIT'], 'deletions_limit'), (bot.types.UsernameChangeReason['LANGUAGE_STATS_VIEWS_LIMIT'], 'language_stats_views_limit'), (bot.types.UsernameChangeReason['LANGUAGE_STATS_VIEWS_DIFFERENCE_LIMIT'], 'language_stats_views_difference_limit'), (bot.types.UsernameChangeReason['VIEWS_BY_SOURCE_STATS_LIMIT'], 'views_by_source_stats_limit'), (bot.types.UsernameChangeReason['VIEWS_BY_SOURCE_STATS_DIFFERENCE_LIMIT'], 'views_by_source_stats_difference_limit'), (bot.types.UsernameChangeReason['THIRD_PARTY_REQUEST'], 'third_party_request')], max_length=64, null=True, verbose_name='reason')),
                ('value', models.PositiveBigIntegerField(verbose_name='value')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.channel', verbose_name='channel')),
            ],
            options={
                'verbose_name': 'excess',
                'verbose_name_plural': 'excesses',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Limitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_utc')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('type', models.CharField(choices=[(bot.types.LimitationType['POST_VIEWS'], 'limitation_type_post_views'), (bot.types.LimitationType['LANGUAGE_STATS'], 'limitation_type_language_stats'), (bot.types.LimitationType['VIEWS_BY_SOURCE_STATS'], 'limitation_type_views_by_source_stats')], max_length=32, verbose_name='type')),
                ('action', models.CharField(choices=[(bot.types.LimitationAction['DELETE_POST'], 'limitation_action_delete_post'), (bot.types.LimitationAction['CHANGE_USERNAME'], 'limitation_action_change_username')], max_length=32, verbose_name='action')),
                ('views', models.PositiveBigIntegerField(default=0, verbose_name='limitation_views')),
                ('views_difference', models.PositiveSmallIntegerField(default=0, verbose_name='limitation_views_difference')),
                ('views_difference_interval', models.PositiveSmallIntegerField(default=60, verbose_name='limitation_views_difference_interval_minutes')),
                ('stats_restrictions', models.TextField(blank=True, help_text='stats_restrictions_help_text', null=True, verbose_name='stats_restrictions')),
                ('hourly_distribution', models.BooleanField(default=False, help_text='hourly_distribution_help_text', verbose_name='hourly_distribution')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start_date_utc')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end_date_utc')),
                ('start_after_days', models.PositiveIntegerField(default=0, verbose_name='start_after_days')),
                ('end_after_days', models.PositiveIntegerField(default=0, verbose_name='end_after_days')),
                ('end_after_limitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_after_limitation_self', to='bot.limitation', verbose_name='end_after_limitation')),
                ('start_after_limitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_after_limitation_self', to='bot.limitation', verbose_name='start_after_limitation')),
            ],
            options={
                'verbose_name': 'limitation',
                'verbose_name_plural': 'limitations',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ChannelLimitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.channel', verbose_name='channel')),
                ('limitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.limitation', verbose_name='limitation')),
            ],
            options={
                'verbose_name': 'limitation',
                'verbose_name_plural': 'limitations',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='limitations',
            field=models.ManyToManyField(blank=True, through='bot.ChannelLimitation', to='bot.limitation', verbose_name='limitations'),
        ),
        migrations.CreateModel(
            name='PostCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(verbose_name='post_date_utc')),
                ('last_check', models.DateTimeField(auto_now_add=True, verbose_name='last_check_utc')),
                ('post_id', models.BigIntegerField(verbose_name='id')),
                ('views', models.PositiveBigIntegerField(verbose_name='views')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.channel', verbose_name='channel')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ('-post_date',),
            },
        ),
        migrations.CreateModel(
            name='StatsViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_utc')),
                ('type', models.CharField(choices=[(bot.types.StatsViewsType['LANGUAGE'], 'stats_views_type_language'), (bot.types.StatsViewsType['VIEWS_BY_SOURCE'], 'stats_views_type_views_by_source')], max_length=32, verbose_name='type')),
                ('key', models.CharField(blank=True, max_length=32, null=True, verbose_name='key')),
                ('value', models.PositiveBigIntegerField(verbose_name='value')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.channel', verbose_name='channel')),
            ],
            options={
                'verbose_name': 'view',
                'verbose_name_plural': 'views',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_utc')),
                ('type', models.CharField(choices=[(bot.types.LogType['DELETION'], 'deletion'), (bot.types.LogType['USERNAME_CHANGE'], 'username_change')], max_length=16, verbose_name='type')),
                ('post_id', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='post_id')),
                ('post_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='post_date_utc')),
                ('post_views', models.PositiveBigIntegerField(blank=True, default=None, null=True, verbose_name='post_views')),
                ('reason', models.CharField(blank=True, choices=[(bot.types.UsernameChangeReason['DELETIONS_LIMIT'], 'deletions_limit'), (bot.types.UsernameChangeReason['LANGUAGE_STATS_VIEWS_LIMIT'], 'language_stats_views_limit'), (bot.types.UsernameChangeReason['LANGUAGE_STATS_VIEWS_DIFFERENCE_LIMIT'], 'language_stats_views_difference_limit'), (bot.types.UsernameChangeReason['VIEWS_BY_SOURCE_STATS_LIMIT'], 'views_by_source_stats_limit'), (bot.types.UsernameChangeReason['VIEWS_BY_SOURCE_STATS_DIFFERENCE_LIMIT'], 'views_by_source_stats_difference_limit'), (bot.types.UsernameChangeReason['THIRD_PARTY_REQUEST'], 'third_party_request')], max_length=64, null=True, verbose_name='reason')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='comment')),
                ('error_message', models.CharField(blank=True, max_length=256, null=True, verbose_name='error_message')),
                ('success', models.BooleanField(default=True, verbose_name='success')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.channel', verbose_name='channel')),
                ('limitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.limitation', verbose_name='limitation')),
                ('userbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.userbot')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.userbot', verbose_name='owner'),
        ),
        migrations.CreateModel(
            name='UserBotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_utc')),
                ('mode', models.PositiveSmallIntegerField(default=1, verbose_name='mode')),
                ('ping_time', models.DateTimeField(auto_now_add=True, verbose_name='ping_time_utc')),
                ('authorization', models.CharField(blank=True, max_length=1024, null=True)),
                ('channels', models.ManyToManyField(blank=True, to='bot.channel', verbose_name='channels')),
                ('userbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.userbot', verbose_name='userbot')),
            ],
        ),
    ]
