# Generated by Django 5.0.7 on 2024-07-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='admins',
        ),
        migrations.AddField(
            model_name='limitation',
            name='type',
            field=models.CharField(choices=[('POST_VIEWS', 'limitation_post_views'), ('LANGUAGE_STATS', 'limitation_language_stats')], default='POST_VIEWS', max_length=32, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='limitation',
            old_name='views_difference_for_deletion',
            new_name='views_difference',
        ),
        migrations.RenameField(
            model_name='limitation',
            old_name='views_difference_for_deletion_interval',
            new_name='views_difference_interval',
        ),
        migrations.RenameField(
            model_name='limitation',
            old_name='views_for_deletion',
            new_name='views',
        ),
    ]
