# Generated by Django 5.0.3 on 2024-03-31 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitation',
            name='views_restricted_for_deletion',
            field=models.PositiveBigIntegerField(default=0, verbose_name='views_restricted_for_deletion'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='delete_albums',
            field=models.BooleanField(default=True, verbose_name='delete_albums'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='delete_posts_after_days',
            field=models.PositiveSmallIntegerField(default=90, verbose_name='delete_all_posts_after_days'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='deletions_count_for_username_change',
            field=models.PositiveSmallIntegerField(default=0, help_text='deletions_count_for_username_change_help_text', verbose_name='deletions_count_for_username_change'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='has_protected_content',
            field=models.BooleanField(default=False, verbose_name='has_protected_content'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='history_days_limit',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='history_days_limit'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='last_username_change',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='last_username_change_utc'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='republish_today_posts',
            field=models.BooleanField(default=True, verbose_name='republish_today_deleted_posts'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='allowed_languages',
            field=models.CharField(blank=True, help_text='allowed_languages_help_text', max_length=256, null=True, verbose_name='allowed_languages'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.channel', verbose_name='channel'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_utc'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='end_after_days',
            field=models.PositiveIntegerField(default=0, verbose_name='end_after_days'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end_date_utc'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='lang_stats_restrictions',
            field=models.BooleanField(default=False, verbose_name='lang_stats_restrictions'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='start_after_days',
            field=models.PositiveIntegerField(default=0, verbose_name='start_after_days'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start_date_utc'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='views_difference_for_deletion',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='views_difference_for_deletion'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='views_for_deletion',
            field=models.PositiveBigIntegerField(default=0, verbose_name='views_for_deletion'),
        ),
        migrations.AlterField(
            model_name='log',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.channel', verbose_name='channel'),
        ),
        migrations.AlterField(
            model_name='log',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_utc'),
        ),
        migrations.AlterField(
            model_name='log',
            name='post_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='post_date_utc'),
        ),
        migrations.AlterField(
            model_name='log',
            name='post_views',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True, verbose_name='post_views'),
        ),
        migrations.AlterField(
            model_name='log',
            name='success',
            field=models.BooleanField(default=True, verbose_name='success'),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('DELETION', 'deletion'), ('USERNAME_CHANGE', 'username_change')], max_length=16, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='post',
            name='limitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.limitation', verbose_name='limitation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(verbose_name='post_date_utc'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.BigIntegerField(verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.PositiveBigIntegerField(verbose_name='views'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='admins',
            field=models.TextField(blank=True, help_text='admins_help_text', max_length=256, null=True, verbose_name='admin_list'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='chatlist_invite',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='chatlist_invite'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='check_post_deletions_interval',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='check_post_deletions_interval_seconds'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='check_post_views_interval',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='check_post_views_interval_seconds'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='delete_old_posts_interval',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='delete_old_posts_interval_minutes'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='individual_allocations',
            field=models.BooleanField(default=False, verbose_name='individual_allocations'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='username_change_cooldown',
            field=models.PositiveSmallIntegerField(default=120, verbose_name='username_change_cooldown_minutes'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='username_suffix_length',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='username_suffix_length'),
        ),
        migrations.AlterField(
            model_name='userbot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_utc'),
        ),
        migrations.AlterField(
            model_name='userbot',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='userbot',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='userbot',
            name='phone_number',
            field=models.CharField(max_length=32, unique=True, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='userbot',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
