# Generated by Django 5.0.3 on 2024-03-31 23:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_limitation_views_restricted_for_deletion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='ping_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='ping_time_utc'),
            preserve_default=False,
        ),
    ]
