# Generated by Django 5.0.7 on 2024-07-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_limitation_views_difference_for_deletion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='userbots_chat_invite',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='userbots_chat_invite'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='views',
            field=models.PositiveBigIntegerField(default=0, verbose_name='limitation_views'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='views_difference',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='limitation_views_difference'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='views_difference_interval',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='limitation_views_difference_interval_minutes'),
        ),
    ]
