# Generated by Django 5.0.7 on 2024-07-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_settings_userbots_chat_invite_alter_limitation_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='dummy',
            field=models.BooleanField(default=False, verbose_name='dummy'),
        ),
    ]
