# Generated by Django 5.0.6 on 2024-06-12 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_userbot_ping_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitation',
            name='views_difference_for_deletion_interval',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='views_difference_for_deletion_interval_minutes'),
        ),
        migrations.AddField(
            model_name='log',
            name='post_id',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='post_id'),
        ),
        migrations.AddField(
            model_name='post',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.channel', verbose_name='channel'),
        ),
        migrations.AddField(
            model_name='post',
            name='last_check',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last_check_utc'),
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='PostCheck',
        ),
    ]
