# Generated by Django 4.2.4 on 2023-09-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_channel_delete_posts_after_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('DELETION', '🗑️ Deletion'), ('USERNAME_CHANGE', '👤 Username change')], max_length=16, verbose_name='Type'),
        ),
    ]
