# Generated by Django 5.0.7 on 2024-08-01 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_log_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='dummy',
        ),
        migrations.AddField(
            model_name='log',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='comment'),
        ),
        migrations.CreateModel(
            name='Excess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_utc')),
                ('type', models.CharField(choices=[('DELETION', 'deletion'), ('USERNAME_CHANGE', 'username_change')], max_length=16, verbose_name='type')),
                ('value', models.PositiveBigIntegerField(verbose_name='value')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.channel', verbose_name='channel')),
            ],
            options={
                'verbose_name': 'excess',
                'verbose_name_plural': 'excesses',
                'ordering': ('-created',),
            },
        ),
    ]
