# Generated by Django 5.0.6 on 2024-06-16 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_limitation_views_difference_for_deletion_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitation',
            name='allowed_languages',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='views_restricted_for_deletion',
        ),
        migrations.RemoveField(
            model_name='postcheck',
            name='limitation',
        ),
        migrations.AddField(
            model_name='limitation',
            name='hourly_distribution',
            field=models.BooleanField(default=False, help_text='hourly_distribution_help_text', verbose_name='hourly_distribution'),
        ),
        migrations.AddField(
            model_name='settings',
            name='archive_channel',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='archive_channel_id'),
        ),
        migrations.AddField(
            model_name='settings',
            name='check_stats_interval',
            field=models.PositiveSmallIntegerField(default=120, verbose_name='check_stats_interval_seconds'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='lang_stats_restrictions',
            field=models.TextField(blank=True, help_text='lang_stats_restrictions_help_text', max_length=256, null=True, verbose_name='lang_stats_restrictions'),
        ),
        migrations.CreateModel(
            name='StatsViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_utc')),
                ('language', models.CharField(blank=True, max_length=32, null=True, verbose_name='language')),
                ('value', models.PositiveBigIntegerField(verbose_name='value')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.channel', verbose_name='channel')),
            ],
            options={
                'verbose_name': 'view',
                'verbose_name_plural': 'views',
                'ordering': ('-created',),
            },
        ),
    ]
