# Generated by Django 4.2.4 on 2023-09-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='history_days',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='History days'),
        ),
    ]
