# Generated by Django 4.2.4 on 2023-09-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_channel_history_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitation',
            name='no_end_date',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='no_start_date',
        ),
    ]
