# Generated by Django 5.0.6 on 2024-07-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_limitation_allowed_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.userbot', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='log',
            name='error_message',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='error_message'),
        ),
        migrations.AddField(
            model_name='log',
            name='reason',
            field=models.CharField(blank=True, choices=[('DELETIONS_LIMIT', 'deletions_limit'), ('LANGUAGE_STATS_VIEWS_LIMIT', 'language_stats_views_limit'), ('LANGUAGE_STATS_VIEWS_DIFFERENCE_LIMIT', 'language_stats_views_difference_limit'), ('THIRD_PARTY_REQUEST', 'third_party_request')], max_length=64, null=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='individual_allocations',
            field=models.BooleanField(default=False, help_text='individual_allocations_help_text', verbose_name='individual_allocations'),
        ),
    ]
