# Generated by Django 6.0 on 2025-12-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_log_dummy_log_comment_excess'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='channels',
            field=models.ManyToManyField(blank=True, to='bot.channel', verbose_name='channels'),
        ),
    ]
