# Generated by Django 4.2.4 on 2023-09-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_limitation_no_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='post_views',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True, verbose_name='Post views'),
        ),
    ]
