# Generated by Django 4.2.4 on 2023-09-04 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_log_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='allowed_languages',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='change_username',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='history_days',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='track_posts_after_days',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='views_difference_for_deletion',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='views',
        ),
        migrations.RemoveField(
            model_name='post',
            name='channel',
        ),
        migrations.AddField(
            model_name='channel',
            name='history_days_limit',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='History days limit'),
        ),
        migrations.AddField(
            model_name='channel',
            name='last_username_change',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='🕐 Last username change, UTC'),
        ),
        migrations.AddField(
            model_name='limitation',
            name='allowed_languages',
            field=models.CharField(blank=True, help_text='List of allowed languages separated by spaces\nIf other languages views count is more than allowed views count, the post will be deleted', max_length=256, null=True, verbose_name='Allowed languages'),
        ),
        migrations.AddField(
            model_name='limitation',
            name='end_after_days',
            field=models.PositiveIntegerField(default=0, verbose_name='End after days'),
        ),
        migrations.AddField(
            model_name='limitation',
            name='lang_stats_restrictions',
            field=models.BooleanField(default=True, verbose_name='Language stats restrictions'),
        ),
        migrations.AddField(
            model_name='limitation',
            name='start_after_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Start after days'),
        ),
        migrations.AddField(
            model_name='limitation',
            name='views_difference_for_deletion',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Views difference for deletion, %'),
        ),
        migrations.AddField(
            model_name='limitation',
            name='views_for_deletion',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Views for deletion'),
        ),
        migrations.AddField(
            model_name='log',
            name='success',
            field=models.BooleanField(default=True, verbose_name='Success'),
        ),
        migrations.AddField(
            model_name='post',
            name='limitation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot.limitation', verbose_name='Limitation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='check_post_deletions_interval',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Check post deletions interval, seconds'),
        ),
        migrations.AddField(
            model_name='settings',
            name='check_post_views_interval',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Check post views interval, seconds'),
        ),
        migrations.AddField(
            model_name='settings',
            name='delete_old_posts_interval',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Delete old posts interval, minutes'),
        ),
        migrations.AddField(
            model_name='settings',
            name='username_change_cooldown',
            field=models.PositiveSmallIntegerField(default=120, verbose_name='Username change cooldown, minutes'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='delete_posts_after_days',
            field=models.PositiveSmallIntegerField(default=90, verbose_name='Delete all posts after days'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='deletions_count_for_username_change',
            field=models.PositiveSmallIntegerField(default=0, help_text='If the number of deletions is less than this value, the username will not be changed\nIf 0, the username will not be changed', verbose_name='Deletions count for username change'),
        ),
    ]
